<a href="https://colab.research.google.com/github/JananiGovuri/Natural-Language-Processing-/blob/main/HW4Code_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn.functional as F
import math

# -------------------------------
# 1. Scaled Dot-Product Attention Function
# -------------------------------
def scaled_dot_product_attention(Q, K, V):
    d_k = Q.size(-1)

    # Compute raw scores
    scores = torch.matmul(Q, K.transpose(-2, -1))

    # Without scaling (for comparison)
    unscaled_softmax = F.softmax(scores, dim=-1)

    # Apply scaling
    scaled_scores = scores / math.sqrt(d_k)

    # Softmax after scaling
    attn_weights = F.softmax(scaled_scores, dim=-1)

    # Final output
    output = torch.matmul(attn_weights, V)

    return output, attn_weights, scores, scaled_scores, unscaled_softmax

# -------------------------------
# 2. Test with Random Q, K, V
# -------------------------------
torch.manual_seed(0)

batch_size = 1
seq_len = 4
d_k = 8

Q = torch.randn(batch_size, seq_len, d_k)
K = torch.randn(batch_size, seq_len, d_k)
V = torch.randn(batch_size, seq_len, d_k)

# Run attention
output, attn_weights, scores, scaled_scores, unscaled_softmax = scaled_dot_product_attention(Q, K, V)

# -------------------------------
# 3. Print Results
# -------------------------------
print("=== Raw Scores (QK^T) ===")
print(scores)

print("\n=== Softmax WITHOUT Scaling ===")
print(unscaled_softmax)

print("\n=== Scaled Scores ===")
print(scaled_scores)

print("\n=== Attention Weights (WITH Scaling) ===")
print(attn_weights)

print("\n=== Output Vectors ===")
print(output)

=== Raw Scores (QK^T) ===
tensor([[[-0.0146,  5.1091, -0.3921, -3.7779],
         [ 0.4648,  0.5446, -0.7034,  0.9571],
         [ 1.3816, -7.0338, -0.2771,  2.2690],
         [ 0.6756,  3.8463, -1.2603, -2.3062]]])

=== Softmax WITHOUT Scaling ===
tensor([[[5.8939e-03, 9.8993e-01, 4.0409e-03, 1.3678e-04],
         [2.4813e-01, 2.6875e-01, 7.7146e-02, 4.0597e-01],
         [2.7628e-01, 6.1181e-05, 5.2604e-02, 6.7106e-01],
         [3.9970e-02, 9.5224e-01, 5.7673e-03, 2.0266e-03]]])

=== Scaled Scores ===
tensor([[[-0.0052,  1.8063, -0.1386, -1.3357],
         [ 0.1643,  0.1926, -0.2487,  0.3384],
         [ 0.4885, -2.4868, -0.0980,  0.8022],
         [ 0.2389,  1.3599, -0.4456, -0.8154]]])

=== Attention Weights (WITH Scaling) ===
tensor([[[0.1211, 0.7410, 0.1060, 0.0320],
         [0.2577, 0.2651, 0.1705, 0.3067],
         [0.3360, 0.0171, 0.1869, 0.4599],
         [0.2032, 0.6235, 0.1025, 0.0708]]])

=== Output Vectors ===
tensor([[[-1.2940, -0.1495, -0.3701, -0.2156, -0.9138,  1.06